spring.application.name=avefenixapp
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/avefenixdb
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect --no es necesario, ahora se autodetecta.
